shop_cart/urls.py
from django.urls import path
from . import views

app_name = "cart"


urlpatterns = [
    path("", views.cart_detail, name="detail"),
    path("add/<int:id>/", views.add_cart, name="add"),
    path("delete/<int:id>/", views.remove_cart, name="remove"),
    path("add-to-compare-list/<int:id>/", views.add_to_compare_list, name="compare"),
    path("compare-list/", views.compare_list, name="compare_list"),
    path("add-single/<int:id>/", views.add_single, name="add_sin"),
    path("remove-single/<int:id>/", views.remove_single, name="rem_sin"),
]

shop_order/urls.py
from django.urls import path

from . import views

app_name = "order"


urlpatterns = [
    path("order/detail/<int:id>/", views.order_detail, name="detail"),
    path("order/create/", views.create_order, name="create"),
    path("order-list/", views.order_list, name="list"),
    path("coupon/<int:id>/", views.coupon_order, name="coupon"),
    path("request/<int:price>/<int:order_id>/", views.send_request, name="request"),
    path("verify/", views.verify, name="verify"),
]

weblog/urls.py
# Standard library import
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

# 3rd-party impoart
from dj_rest_auth.views import PasswordResetConfirmView
from rest_framework_simplejwt import views as jwt_views


urlpatterns = [
    path("secret-admin-panel/", admin.site.urls),
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("", include("shop_core.urls", namespace="core")),
    path("", include("shop_product.urls", namespace="product")),
    path("", include("shop_account.urls", namespace="account")),
    path("cart/", include("shop_cart.urls", namespace="cart")),
    path("", include("shop_order.urls", namespace="order")),
    path("", include("shop_contact.urls", namespace="contact")),
    path("captcha/", include("captcha.urls")),
    path("accounts/", include("allauth.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("celery-progress/", include("celery_progress.urls")),
    # path('api-auth/', include('rest_framework.urls')),
    # path('api/token-auth/', views.obtain_auth_token),
    path("api/rest-auth/", include("dj_rest_auth.urls")),
    path("api/rest-auth/registration/", include("dj_rest_auth.registration.urls")),
    path(
        "api/rest-auth/password/reset/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "api/token/", jwt_views.TokenObtainPairView.as_view(), name="token_obtain_pair"
    ),
    path(
        "api/token/refresh/", jwt_views.TokenRefreshView.as_view(), name="token_refresh"
    ),
]

handler404 = "shop_product.views.page_not_found"


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

shop_cart/models.py
# Core Django imports
from django.db import models
from django.conf import settings

# Local imports
from shop_product.models import (
    Product,
    Variant,
    TimeStamp,
)


class Cart(TimeStamp):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variant = models.ForeignKey(
        Variant, on_delete=models.CASCADE, null=True, blank=True
    )
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.user.username} - {self.product.title}"


class Compare(TimeStamp):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    session_key = models.CharField(max_length=177, unique=True, blank=True, null=True)

    def __str__(self):
        return self.product.title

shop_cart/forms.py
from django import forms
from .models import Compare, Cart


class CartForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["quantity"].required = True
        self.fields["quantity"].error_messages.update(
            {"required": "This field is required"}
        )

    class Meta:
        model = Cart
        fields = ("quantity",)


class CompareForm(forms.ModelForm):
    class Meta:
        model = Compare
        fields = ("product",)

shop_cart/views.py
# Core Django imports
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Local imports
from shop_order.forms import OrderForm
from shop_product.models import Product, Variant
from .models import Cart, Compare
from .forms import CartForm


@login_required(login_url="account:sign_in")
def cart_detail(request):
    cart = Cart.objects.filter(user_id=request.user.id)
    form = OrderForm()
    return render(request, "cart/detail.html", {"cart": cart, "form": form})


@login_required(login_url="account:sign_in")
def add_cart(request, id):
    url = request.META.get("HTTP_REFERER")
    product = Product.objects.get(id=id)
    if product.status != None:
        var_id = request.POST.get("select")
        data = Cart.objects.filter(user_id=request.user.id, variant_id=var_id)
        if data:
            check = "yes"
        else:
            check = "no"
    else:
        data = Cart.objects.filter(user_id=request.user.id, product_id=id)
        if data:
            check = "yes"
        else:
            check = "no"

    if request.method == "POST":
        form = CartForm(request.POST)
        if form.is_valid():
            info = form.cleaned_data["quantity"]
            var_id = request.POST.get("select")
            if check == "yes":
                if product.status is not None:
                    shop = Cart.objects.get(
                        user_id=request.user.id, product_id=id, variant_id=var_id
                    )
                else:
                    shop = Cart.objects.get(user_id=request.user.id, product_id=id)
                shop.quantity += info
                shop.save()
            else:
                Cart.objects.create(
                    user_id=request.user.id,
                    product_id=id,
                    variant_id=var_id,
                    quantity=info,
                )
        return redirect(url)


@login_required(login_url="account:sign_in")
def remove_cart(request, id):
    url = request.META.get("HTTP_REFERER")
    cart = Cart.objects.get(id=id)
    cart.delete()
    return redirect(url)


def add_to_compare_list(request, id):
    url = request.META.get("HTTP_REFERER")
    if request.user.is_authenticated:
        item = get_object_or_404(Product, id=id)
        qs = Compare.objects.filter(user_id=request.user.id, product_id=id)
        if qs.exists():
            messages.error(
                request, "This item has already exists in your compare list", "warning"
            )
        else:
            Compare.objects.create(user_id=request.user.id, product_id=id)
    else:
        item = get_object_or_404(Product, id=id)
        qs = Compare.objects.filter(
            user_id=None, product_id=id, session_key=request.session.session_key
        )
        if qs.exists():
            messages.error(
                request, "This item has already exists in your compare list", "warning"
            )
        else:
            if not request.session.session_key:
                request.session.create()
            Compare.objects.create(
                user_id=None, product_id=id, session_key=request.session.session_key
            )
    return redirect(url)


def compare_list(request):
    if request.user.is_authenticated:
        data = Compare.objects.filter(user_id=request.user.id)
        return render(request, "cart/compare_list.html", {"data": data})
    else:
        data = Compare.objects.filter(
            session_key=request.session.session_key, user_id=None
        )
        return render(request, "cart/compare_list.html", {"data": data})


@login_required(login_url="account:sign_in")
def add_single(request, id):
    url = request.META.get("HTTP_REFERER")
    cart = Cart.objects.get(id=id)
    if cart.product.status is not None:
        variant = Variant.objects.get(id=cart.variant.id)
        if variant.amount > cart.quantity:
            cart.quantity += 1
            cart.save()
    else:
        product = Product.objects.get(id=cart.product.id)
        if product.amount > cart.quantity:
            cart.quantity += 1
            cart.save()
    return redirect(url)


@login_required(login_url="account:sign_in")
def remove_single(request, id):
    url = request.META.get("HTTP_REFERER")
    cart = Cart.objects.get(id=id)
    if cart.quantity < 2:
        cart.delete()
    else:
        cart.quantity -= 1
        cart.save()
    return redirect(url)

shop_cart/templates/cart/compare_list.html
{% extends 'base/base.html' %}
{% load humanize %}

{% block title %} Compare List {% endblock %}


{% block content %}
  <!-- Page Content -->
  <div class="container">


    <ol class="breadcrumb">
      <li class="breadcrumb-item">
      </li>
      <li class="breadcrumb-item active">Compare List</li>
    </ol>

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">

        <!-- Blog Post -->
        {% for d in data %}
        <div class="card mb-4">
            <img class="card-img-top" src="{{ d.product.image.url }}" alt="Card image cap" style="width: 177px;">
            <div class="card-body">
              <h2 class="card-title"><a href="{{ d.get_absolute_url }}">{{ d.product.title }}</a></h2>
              <p class="card-text"></p>
              <a href="{{ d.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
            </div>
            <div class="card-footer text-muted">
              {{ d.product.unit_price|intcomma }} Toman
            </div>
          </div>
        {% endfor %}
          
          
        </ul>

        </div>
      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
{% endblock %}

shop_cart/templates/cart/detail.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block title %} Cart Detail {% endblock %}


{% block content %}
    <div class="container">
        <table class="table table-dark">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Image</th>
                <th scope="col">Name</th>
                <th scope="col">Price</th>
                <th scope="col">Size</th>
                <th scope="col">Color</th>
                <th scope="col">quantity</th>
                <th scope="col">Total Price</th>
                <th scope="col">Delete</th>
              </tr>
            </thead>
            <tbody>
            {% for c in cart %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><img src="{{ c.product.image.url }}" style="width: 99px;"></td>
                <td>{{ c.product.title }}</td>
                <td>
                {% if product.status is not None %}
                  {{ c.variant.total_price }}
                {% else %}
                  {{ c.product.total_price }}
                {% endif %}
                </td>   
                <td>{{ c.variant.size_variant }}</td>
                <td>{{ c.variant.color_variant }}</td>
                <td>
                  <a href="{% url 'cart:rem_sin' c.id %}">remove</a>
                  {{ c.quantity }}
                  <a href="{% url 'cart:add_sin' c.id %}">Add</a>
                </td>
                <td>
                    {% if product.status is not None %}
                        {% widthratio c.variant.total_price 1 c.quantity %}
                    {% else %}
                        {% widthratio c.product.total_price 1 c.quantity %}
                    {% endif %}
                </td>
                <td><a href="{% url 'cart:remove' c.id %}">Delete</a></td>
              </tr>
              {% empty %}
              <h4 class="alert alert-warning">Your Cart is empty</h4>
            {% endfor %}
            </tbody>
          </table>

          {% if cart|length > 0 %}
          <form method="POST" action="{% url 'order:create' %}" novalidate>
            {% csrf_token %}
            {{ form.address|as_crispy_field }}
            <button type="submit" class="btn btn-outline-primary">Confirm</button>
          </form>
          {% endif %}
    </div>
{% endblock %}