shop_account/urls.py
from django.urls import path
from . import views

app_name = "account"


urlpatterns = [
    path("account/sign-in/", views.SignIn.as_view(), name="sign_in"),
    path("account/sign-up/", views.SignUp.as_view(), name="sign_up"),
    path("activate/<uidb64>/<token>/", views.ActiveEmail.as_view(), name="activate"),
    path("log-out/", views.Logout.as_view(), name="log_out"),
    path("profile/", views.UserProfile.as_view(), name="profile"),
    path("change-password/", views.ChangePassword.as_view(), name="change_pass"),
    path("user-panel/", views.UserPanel.as_view(), name="user_panel"),
    path("password-reset/", views.ResetPassword.as_view(), name="reset"),
    path("password-done/", views.DonePassword.as_view(), name="done"),
    path(
        "confirm-password/<uidb64>/<token>/",
        views.ConfirmPassword.as_view(),
        name="confirm",
    ),
    path(
        "complete-reset-password/", views.CompeletePassword.as_view(), name="complete"
    ),
    path("purchase-history/", views.history, name="history"),
]

shop_cart/urls.py
from django.urls import path
from . import views

app_name = "cart"


urlpatterns = [
    path("", views.cart_detail, name="detail"),
    path("add/<int:id>/", views.add_cart, name="add"),
    path("delete/<int:id>/", views.remove_cart, name="remove"),
    path("add-to-compare-list/<int:id>/", views.add_to_compare_list, name="compare"),
    path("compare-list/", views.compare_list, name="compare_list"),
    path("add-single/<int:id>/", views.add_single, name="add_sin"),
    path("remove-single/<int:id>/", views.remove_single, name="rem_sin"),
]

shop_contact/urls.py
from django.urls import path
from . import views

app_name = "contact"


urlpatterns = [
    path("contact-us/", views.contact_view, name="contact"),
]

shop_core/urls.py
from django.urls import path
from . import views

app_name = "core"


urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("progress/", views.ProgressBar.as_view(), name="progress"),
    path("bucket-list/", views.BucketList.as_view(), name="bucket_list"),
    path(
        "delete-bucket/<str:key>/", views.DeleteBucket.as_view(), name="delete_bucket"
    ),
    path(
        "download-bucket/<str:key>/",
        views.DownloadBucket.as_view(),
        name="download_bucket",
    ),
]

weblog/urls.py
# Standard library import
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

# 3rd-party impoart
from dj_rest_auth.views import PasswordResetConfirmView
from rest_framework_simplejwt import views as jwt_views


urlpatterns = [
    path("secret-admin-panel/", admin.site.urls),
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("", include("shop_core.urls", namespace="core")),
    path("", include("shop_product.urls", namespace="product")),
    path("", include("shop_account.urls", namespace="account")),
    path("cart/", include("shop_cart.urls", namespace="cart")),
    path("", include("shop_order.urls", namespace="order")),
    path("", include("shop_contact.urls", namespace="contact")),
    path("captcha/", include("captcha.urls")),
    path("accounts/", include("allauth.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("celery-progress/", include("celery_progress.urls")),
    # path('api-auth/', include('rest_framework.urls')),
    # path('api/token-auth/', views.obtain_auth_token),
    path("api/rest-auth/", include("dj_rest_auth.urls")),
    path("api/rest-auth/registration/", include("dj_rest_auth.registration.urls")),
    path(
        "api/rest-auth/password/reset/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "api/token/", jwt_views.TokenObtainPairView.as_view(), name="token_obtain_pair"
    ),
    path(
        "api/token/refresh/", jwt_views.TokenRefreshView.as_view(), name="token_refresh"
    ),
]

handler404 = "shop_product.views.page_not_found"


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

shop_core/views.py
# Core Django imports
from django.shortcuts import redirect, render
from django.db.models import Sum
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

# Local imports
from shop_slider.models import Slider
from shop_cart.models import Cart
from shop_product.models import Product
from . import tasks


class Index(View):
    template_name = "base/index.html"

    def get(self, request):
        # tasks.send_mail.delay()
        slider = Slider.objects.all()
        cart_nums = Cart.objects.filter(user_id=request.user.id).aggregate(
            sum=Sum("quantity")
        )["sum"]
        latest = Product.objects.order_by("-created")[:6]
        context = {"slider": slider, "cart_nums": cart_nums, "latest": latest}
        return render(request, self.template_name, context)


class BucketList(LoginRequiredMixin, View):
    template_name = "base/bucket.html"
    login_url = "account:sign-in"

    def get(self, request):
        objects = tasks.get_objects_list_tasks()
        return render(request, self.template_name, {"objects": objects})


class DeleteBucket(LoginRequiredMixin, View):
    login_url = "account:sign-in"

    def get(self, request, key):
        tasks.delete_object_tasks.delay(key)
        messages.success(request, "Your demand wil be answered soon", "success")
        return redirect(request.META.get("HTTP_REFERER"))


class DownloadBucket(LoginRequiredMixin, View):
    login_url = "account:sign-in"

    def get(self, request, key):
        tasks.download_object_tasks.delay(key)
        messages.success(request, "Your demand wil be answered soon", "success")
        return redirect(request.META.get("HTTP_REFERER"))


class ProgressBar(View):
    template_name = "base/progress.html"

    def get(self, request):
        task = tasks.go_to_sleep.delay(1)
        return render(request, self.template_name, {"task_id": task.task_id})

shop_core/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/modern-business.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/body.css' %}">
</head>
<body class="main">
{% include 'base/nav.html' %}
{% include 'base/messages.html' %}
{% block content %}{% endblock %}
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>

shop_core/templates/base/bucket.html
{% extends 'base/base.html' %}
{% load size %}

{% block title %} Bucket List {% endblock %}


{% block content %}
	<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Size</th>
      <th scope="col">Download</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for obj in objects %}
   	<tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ obj.Key }}</td>
      <td>{{ obj.Size|convert }}</td>
      <td><a href="{% url 'core:download_bucket' obj.Key %}">Download</a></td>
      <td><a href="{% url 'core:delete_bucket' obj.Key %}">Delete</a></td>
    </tr>
    {% empty %}
        <p class='alert alert-warning'>Bucket is empty</p>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

shop_core/templates/base/index.html
{% extends 'base/base.html' %}
{% load thumbnail %}
{% load humanize %}

{% block title %} Home {% endblock %}


{% block content %}

<header>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <!-- Slide One - Set the background image for this slide in the line below -->
      {% for s in slider %}
      <div class="carousel-item {{ forloop.first|yesno:'active,' }}" style="background-image: url('{{ s.image.url }}')" style="width: 200px;">
        <div class="carousel-caption d-none d-md-block">
          <h3>{{ s.title }}</h3>
        </div>
      </div>
      {% endfor %}
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</header>
      <!-- Page Content -->
  <div class="container">

    <h1 class="my-4">Home</h1>
    <h3 class="my-4">Latest Products</h3>

    <!-- Portfolio Section -->

    <div class="row">
      
      {% for ls in latest %}
      <div class="col-lg-4 col-sm-6 portfolio-item">
        <div class="card h-100">
          <a href="{{ ls.get_absolute_url }}">
          {% comment %} {% thumbnail ls.image "250x250" crop="center" as im %} {% endcomment %}
            <img class="img-fluid rounded" src="{{ ls.image.url }}" style="width: 177px;" alt="">
          {% comment %} {% endthumbnail %} {% endcomment %}
          </a>
          <div class="card-body">
            <h4 class="card-title">
              <a href="{{ ls.get_absolute_url }}">{{ ls.title }}</a>
            </h4>
            <p>{{ ls.unit_price|intcomma }} Toman</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <!-- /.row -->

  </div>
{% endblock %}

shop_core/templates/base/messages.html
{% if messages %}
    {% for message in messages %}
        <p {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</p>
    {% endfor %}
{% endif %}

shop_core/templates/base/nav.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">Home</a>
      <a class="navbar-brand" href="/products">Products</a>
      <a class="navbar-brand" href="{% url 'contact:contact' %}">Contact Us</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart:detail' %}">Cart {{ cart_nums }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account:user_panel' %}">User Panel</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account:log_out' %}">Log-out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account:sign_up' %}">Sign-Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account:sign_in' %}">Sign-In</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

shop_core/templates/base/progress.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} Progress {% endblock %}


{% block content %}
    <h1>Done!</h1>
    <div class='progress-wrapper'>
        <div id='progress-bar' class='progress-bar' style="background-color: #68a9ef; width: 0%;">&nbsp;</div>
        </div>
    <div id="progress-bar-message">Waiting for progress to start...</div>
    <script src="{% static 'celery_progress/celery_progress.js' %}"></script>
    <script>
    // vanilla JS version
        document.addEventListener("DOMContentLoaded", function () {
        var progressUrl = "{% url 'celery_progress:task_status' task_id %}";
        CeleryProgressBar.initProgressBar(progressUrl);
        });
    </script>
{% endblock %}