shop_cart/urls.py
from django.urls import path
from . import views

app_name = "cart"


urlpatterns = [
    path("", views.cart_detail, name="detail"),
    path("add/<int:id>/", views.add_cart, name="add"),
    path("delete/<int:id>/", views.remove_cart, name="remove"),
    path("add-to-compare-list/<int:id>/", views.add_to_compare_list, name="compare"),
    path("compare-list/", views.compare_list, name="compare_list"),
    path("add-single/<int:id>/", views.add_single, name="add_sin"),
    path("remove-single/<int:id>/", views.remove_single, name="rem_sin"),
]

shop_product/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from .sitemap import ProductSitemap
from . import views

app_name = "product"


sitemaps = {
    "static": ProductSitemap,
}


urlpatterns = [
    path("products/", views.ProductList.as_view(), name="list"),
    path("category/<slug:slug>/", views.ProductList.as_view(), name="category"),
    path("product/<slug:slug>/<int:id>/", views.product_detail, name="detail"),
    path("add-comment/<int:product_id>/", views.add_comment, name="comment"),
    path("add-reply/<int:product_id>/<int:comment_id>/", views.add_reply, name="reply"),
    path("add-to-favourite/<int:id>/", views.add_favourite, name="fav"),
    path("favourite-list/", views.favourite_list, name="fav_list"),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

weblog/urls.py
# Standard library import
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

# 3rd-party impoart
from dj_rest_auth.views import PasswordResetConfirmView
from rest_framework_simplejwt import views as jwt_views


urlpatterns = [
    path("secret-admin-panel/", admin.site.urls),
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("", include("shop_core.urls", namespace="core")),
    path("", include("shop_product.urls", namespace="product")),
    path("", include("shop_account.urls", namespace="account")),
    path("cart/", include("shop_cart.urls", namespace="cart")),
    path("", include("shop_order.urls", namespace="order")),
    path("", include("shop_contact.urls", namespace="contact")),
    path("captcha/", include("captcha.urls")),
    path("accounts/", include("allauth.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("celery-progress/", include("celery_progress.urls")),
    # path('api-auth/', include('rest_framework.urls')),
    # path('api/token-auth/', views.obtain_auth_token),
    path("api/rest-auth/", include("dj_rest_auth.urls")),
    path("api/rest-auth/registration/", include("dj_rest_auth.registration.urls")),
    path(
        "api/rest-auth/password/reset/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "api/token/", jwt_views.TokenObtainPairView.as_view(), name="token_obtain_pair"
    ),
    path(
        "api/token/refresh/", jwt_views.TokenRefreshView.as_view(), name="token_refresh"
    ),
]

handler404 = "shop_product.views.page_not_found"


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

shop_product/models.py
# Core Django imports
from django.db import models
from django.utils.html import format_html
from django.utils.text import slugify
from django.urls import reverse
from django.utils.text import slugify
from django.conf import settings

# 3rd-party imports
from django_jalali.db import models as jmodels
from tinymce import models as tinymce_models


class TimeStamp(models.Model):
    created = jmodels.jDateTimeField(auto_now_add=True, null=True, blank=True)
    updated = jmodels.jDateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        abstract = True


class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField()

    def __str__(self):
        return self.ip_address


class Category(TimeStamp):
    sub_cat = models.ForeignKey(
        "self",
        on_delete=models.CASCADE,
        related_name="s_category",
        blank=True,
        null=True,
    )
    is_sub = models.BooleanField(default=False)
    title = models.CharField(max_length=177)
    slug = models.SlugField(unique=True)

    class Meta(TimeStamp.Meta):
        ordering = ("-created",)
        verbose_name_plural = "Categories"

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse("product:category", args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class Product(TimeStamp):
    class STATUS(models.TextChoices):
        COLOR = "c", "color"
        SIZE = "s", "size"
        NONE = "n", "none"
        # BOTH = 'b', 'both'

    title = models.CharField(max_length=177)
    slug = models.SlugField(unique=True, blank=True)
    description = tinymce_models.HTMLField(blank=True)
    unit_price = models.PositiveIntegerField()
    amount = models.PositiveIntegerField()
    discount = models.PositiveIntegerField(blank=True, null=True)
    total_price = models.PositiveIntegerField(null=True, blank=True)
    image = models.ImageField(default="1.jpg")
    status = models.CharField(max_length=15, blank=True, choices=STATUS.choices)
    available = models.BooleanField(default=True)
    category = models.ManyToManyField(Category, blank=True)
    visit_count = models.ManyToManyField(
        IPAddress, blank=True, related_name="visit_count"
    )
    favourite = models.ManyToManyField(
        settings.AUTH_USER_MODEL, blank=True, related_name="fav"
    )
    sell = models.PositiveIntegerField(default=0)
    brand = models.ForeignKey("Brand", on_delete=models.PROTECT, blank=True, null=True)
    color = models.ManyToManyField("Color", blank=True)
    size = models.ManyToManyField("Size", blank=True)

    class Meta(TimeStamp.Meta):
        ordering = ("-created",)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        self.total_price = self.get_total_price
        super().save(*args, **kwargs)

    @property
    def get_total_price(self):
        if not self.discount:
            return self.unit_price
        elif self.discount:
            total = (self.discount * self.unit_price) / 100
            return int(self.unit_price - total)
        return self.total_price

    def image_thumbnail(self):
        return format_html('<img src="{}" width=77>'.format(self.image.url))

    def get_absolute_url(self):
        return reverse("product:detail", args=[self.slug, self.id])

    def category_to_str(self):
        return "-".join([category.title for category in self.category.all()])

    category_to_str.short_description = "Categories"

    def get_visit_count(self):
        return self.visit_count.count()

    get_visit_count.short_description = "Visit Count"


class Color(models.Model):
    title = models.CharField(max_length=177)

    def __str__(self):
        return self.title


class Size(models.Model):
    title = models.CharField(max_length=177)

    def __str__(self):
        return self.title


class Variant(TimeStamp):
    title = models.CharField(max_length=177)
    product_variant = models.ForeignKey(Product, on_delete=models.PROTECT, null=True)
    size_variant = models.ForeignKey(
        Size, on_delete=models.PROTECT, null=True, blank=True
    )
    color_variant = models.ForeignKey(
        Color, on_delete=models.PROTECT, null=True, blank=True
    )
    unit_price = models.PositiveIntegerField()
    amount = models.PositiveIntegerField()
    discount = models.PositiveIntegerField(blank=True, null=True)
    total_price = models.PositiveIntegerField(null=True, blank=True)
    sell = models.PositiveIntegerField(default=0)

    class Meta(TimeStamp.Meta):
        ordering = ("-created",)

    def __str__(self):
        return self.title

    @property
    def get_total_price(self):
        if not self.discount:
            return self.unit_price
        elif self.discount:
            total = (self.discount * self.unit_price) / 100
            return int(self.unit_price - total)
        return self.total_price

    def save(self, *args, **kwargs):
        self.total_price = self.get_total_price
        super().save(*args, **kwargs)


class Brand(models.Model):
    title = models.CharField(max_length=177)

    def __str__(self):
        return self.title


class Comment(TimeStamp):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    comment = models.TextField()
    status = models.BooleanField(default=False)
    reply = models.ForeignKey(
        "self", on_delete=models.CASCADE, null=True, blank=True, related_name="replies"
    )
    is_reply = models.BooleanField(default=False)

    class Meta(TimeStamp.Meta):
        ordering = ("-created",)

    def __str__(self):
        return f"{self.user.username} - {self.comment[:17]}"

    def children(self):
        return Comment.objects.filter(reply=self)

shop_product/forms.py
from django import forms
from .models import Comment


class SearchForm(forms.Form):
    search = forms.CharField(
        max_length=177, widget=forms.TextInput(attrs={"class": "form-control"})
    )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("comment",)


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("comment",)

shop_product/views.py
# Core Django imports
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.utils.translation import gettext as _
from django.db.models import Max, Min
from django.views import View
from django.db.models import Q
from django.contrib import messages
from django.conf import settings

# Third-party imports
from urllib.parse import urlencode
import redis

# Local imports
from shop_cart.forms import CartForm
from .models import Product, Variant, Comment, Category
from .forms import (
    SearchForm,
    CommentForm,
    ReplyForm,
)
from shop_cart.forms import CompareForm
from .filters import ProductFilter


class ProductList(View):
    template_name = "product/product_list.html"

    def get(self, request, slug=None):
        products = Product.objects.only('id', 'title', 'image', 'unit_price') \
                                    .filter(available=True)
        f = ProductFilter(request.GET, queryset=products)
        products = f.qs
        mx = Product.objects.aggregate(unit_price=Max("unit_price"))
        max_price = str(mx["unit_price"])
        mn = Product.objects.aggregate(unit_price=Min("unit_price"))
        min_price = str(mn["unit_price"])
        compare_form = CompareForm()
        paginator = Paginator(products, 3)
        page_number = request.GET.get("page")
        data = request.GET.copy()
        if "page" in data:
            del data["page"]
        page_obj = paginator.get_page(page_number)
        categories = Category.objects.filter(is_sub=False)
        if slug:
            category = get_object_or_404(Category, slug=slug)
            page_obj = products.filter(category=category)
            paginator = Paginator(page_obj, 3)
            page_number = request.GET.get("page")
            data = request.GET.copy()
            if "page" in data:
                del data["page"]
            page_obj = paginator.get_page(page_number)
        form = SearchForm()
        if "search" in request.GET:
            form = SearchForm(request.GET)
            if form.is_valid():
                info = form.cleaned_data["search"]
                page_obj = products.filter(
                      Q(title__icontains=info)
                    | Q(description__icontains=info)
                    | Q(tag__title__icontains=info)
                )
                paginator = Paginator(page_obj, 3)
                page_number = request.GET.get("page")
                data = request.GET.copy()
                if "page" in data:
                    del data["page"]
                page_obj = paginator.get_page(page_number)
        context = {
            "form": form,
            _("products"): page_obj,
            "categories": categories,
            "compare_form": compare_form,
            "filter": f,
            "max_price": max_price,
            "min_price": min_price,
            "data": urlencode(data),
        }
        return render(request, self.template_name, context)


# redis_con = redis.Redis(settings.REDIS_HOST, settings.REDIS_PORT, settings.REDIS_DB)
def product_detail(request, slug, id):
    product = get_object_or_404(Product, slug=slug, id=id)
    # redis_con.hsetnx('post_views', post.id, 0)
    is_fav = False
    if product.favourite.filter(id=request.user.id).exists():
        is_fav = True
    form = CartForm()
    comment_form = CommentForm()
    reply_form = ReplyForm()
    comment = Comment.objects.filter(product_id=id, is_reply=False, status=True)
    ip_address = request.user.ip_address
    if ip_address not in product.visit_count.all():
        product.visit_count.add(ip_address)
    if product.status is not None:
        if request.method == "POST":
            variant = Variant.objects.filter(product_variant_id=id)
            var_id = request.POST.get("select")
            try:
                variants = Variant.objects.get(id=var_id)
            except Variant.DoesNotExist:
                variants = Variant.objects.none()
            # colors = Variant.objects.filter(product_variant_id=id, size_variant_id=variants.size_variant_id)  # postgresql db
            # size = Variant.objects.filter(product_variant_id=id).distinct('size_variant_id')  # postgresql db
        else:
            variant = Variant.objects.filter(product_variant_id=id)
            try:
                variants = Variant.objects.get(id=id)
            except Variant.DoesNotExist:
                variants = Variant.objects.none()
            # colors = Variant.objects.filter(product_variant_id=id, size_variant_id=variants.size_variant_id)  # postgresql db
            # size = Variant.objects.filter(product_variant_id=id).distinct('size_variant_id')  # postgresql db
        context = {
            "product": product,
            "variant": variant,
            "variants": variants,
            "form": form,
            "comment_form": comment_form,
            "comment": comment,
            "is_fav": is_fav,
            "reply_form": reply_form,
        }
        return render(request, "product/product_detail.html", context)
    else:
        context = {
            "product": product,
            "form": form,
            "comment_form": comment_form,
            "comment": comment,
            "is_fav": is_fav,
            "reply_form": reply_form,
        }
        return render(request, "product/product_detail.html", context)


@login_required(login_url="account:sign_in")
def add_comment(request, product_id):
    url = request.META.get("HTTP_REFERER")
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            Comment.objects.create(
                user_id=request.user.id,
                comment=data["comment"],
                product_id=product_id,
            )
            messages.success(
                request, "after we accept, your comment will show on site", "primary"
            )
        return redirect(url)


@login_required(login_url="account:sign_in")
def add_reply(request, product_id, comment_id):
    if request.method == "POST":
        form = ReplyForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            Comment.objects.create(
                comment=data["comment"],
                product_id=product_id,
                reply_id=comment_id,
                is_reply=True,
                user_id=request.user.id,
            )
        return redirect(request.META.get("HTTP_REFERER"))


@login_required(login_url="account:sign_in")
def add_favourite(request, id):
    url = request.META.get("HTTP_REFERER")
    product = get_object_or_404(Product, id=id)
    is_fav = False
    if product.favourite.filter(id=request.user.id).exists():
        product.favourite.remove(request.user)
        is_fav = False
    else:
        product.favourite.add(request.user)
        is_fav = True
    return redirect(url)


@login_required(login_url="account:sign_in")
def favourite_list(request):
    fa_product = request.user.fav.all()
    paginator = Paginator(fa_product, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "product/fav_list.html", {"product": page_obj})


def page_not_found(request, exception=None):
    return render(request, "product/not_found.html")

shop_product/templates/product/not_found.html
<h2>error 404</h2>
<h4 class="alert alert-danger"> Page Not Found</h4>

shop_product/templates/product/product_detail.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}
{% load thumbnail %}

{% block title %} {{ product.title }} {% endblock %}


{% block content %}
    <!-- Page Content -->
  <div class="container">

    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="index.html">{{ product.title }}</a>
      </li>
    </ol>

    {% if is_fav %}
      <a href="{% url 'product:fav' product.id %}">remove from Favourite</a>
    {% else %}
      <a href="{% url 'product:fav' product.id %}">add to Favourite</a>
    {% endif %}

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Preview Image -->
        {% thumbnail product.image "250x250" crop="center" as im %}
          <img class="img-fluid rounded" src="{{ im.url }}" style="width: 177px;" alt="">
        {% endthumbnail %}

        <hr>

        <!-- Date/Time -->
        <p>{{ product.title }}</p>
        {% comment %} {% if product.status == 'Both' %}
            <form method="POST">
            {% csrf_token %}
            {% for v in colors %}
                <input type="radio" name="select" value="{{ v.id }}"
                {% if variants.id == v.id %} checked {% endif %} required
                onchange="this.form.submit()">
                <a>{{ v.color_variant }}</a>
            {% endfor %}
            </form><br>
            <form method="POST">
              {% csrf_token %}
              {% for v in size %}
                  <input type="radio" name="select" value="{{ v.id }}"
                  {% if variants.id == v.id %} checked {% endif %} required
                  onchange="this.form.submit()">
                  <a>{{ v.size_variant }}</a>
              {% endfor %}
              </form> {% endcomment %}

        {% if product.status == 'Color' %}
            <form method="POST">
            {% csrf_token %}
            {% for v in variant %}
                <input type="radio" name="select" value="{{ v.id }}"
                {% if variants.id == v.id %} checked {% endif %} required
                onchange="this.form.submit()">
                <a>{{ v.color_variant }}</a>
            {% endfor %}
            </form>
        {% elif product.status == 'Size' %}
            <form method="POST">
            {% csrf_token %}
            {% for v in variant %}
                <input type="radio" name="select" value="{{ v.id }}"
                {% if variants.id == v.id %} checked {% endif %} required
                onchange="this.form.submit()">
                <a>{{ v.size_variant }}</a>
            {% endfor %}
            </form>
        {% endif %}
      
        {% if product.status != None %}
          {% if request.user.is_special_user %}
          <h5>price: {{ variants.price_special_user|intcomma }} Toman</h5>
          {% else %}
          <h5>price: {{ variants.total_price|intcomma }} Toman</h5>
          {% endif %}
            <form method="POST" action="{% url 'cart:add' product.id %}">
              {% csrf_token %}
              <input type="hidden" name="select" value="{{ variants.id }}">
              <input type="number" name="quantity" value="1" min="1" max="{{ variants.amount }}"
              required class="form-control" style="width: 17% !important;">
              <button type="submit" class="btn btn-outline-info">Add</button>
            </form>
        {% else %}
          <form method="POST" action="{% url 'cart:add' product.id %}">
            {% csrf_token %}
            <input type="number" name="quantity" value="1" min="1" max="{{ product.amount }}"
            required class="form-control" style="width: 17% !important;">
            <button type="submit" class="btn btn-outline-info">Add</button>
        </form>
        {% endif %}

        <hr><hr>

      </div>

        <form method="POST" action="{% url 'product:comment' product.id %}">
          {% csrf_token %}
          {{ comment_form.comment|as_crispy_field }}
          <button type="submit" class="btn btn-outline-info">Submit</button>
        </form><hr>

      {% for c in comment %}
        <div class="card bg-dark text-white">
          <p class="card-header">{{ c.user.username }} - {{ c.created }}</p>
          <p class="card-body">{{ c.comment }}</p>
        </div><br><br>
        
        <form method="POST" action="{% url 'product:reply' product.id c.id %}">
          {% csrf_token %}
          {{ reply_form.comment|as_crispy_field }}
          <button type="submit" class="btn btn-outline-danger">Submit</button>
        </form><br><br>

        {% for r in c.replies.all %}
        <div class="card bg-dark text-white">
          <p class="card-header">{{ r.user.username }} - {{ r.created }}</p>
          <p class="card-body">{{ r.comment }}</p>
        </div>
        {% endfor %}
      {% endfor %}

      </div>
    </div>
{% endblock %}

shop_product/templates/product/product_list.html
{% extends 'base/base.html' %}
{% load static %}
{% load humanize %}
{% load divide %}
{% load thumbnail %}

{% block title %} Product List {% endblock %}


{% block content %}
  <!-- Page Content -->
  <div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">Products
    </h1>

    <ol class="breadcrumb">
      <li class="breadcrumb-item">
      </li>
      <li class="breadcrumb-item active">Products</li>
    </ol>

    <form>
      <input type="submit" name="unit_price" value="most expensive" class="btn btn-outline-info">
      <input type="submit" name="unit_price" value="most cheap" class="btn btn-outline-info">
      <input type="submit" name="create" value="newest" class="btn btn-outline-info">
      <input type="submit" name="sell" value="most sell" class="btn btn-outline-info">

      <div style="display: none;">
        {{ filter.form.price_gte }}
        {{ filter.form.price_lte }}
        {{ filter.form.brand }}
        {{ filter.form.color }}
        {{ filter.form.size }}
      </div>
    </form>

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">

        <!-- Blog Post -->
        {% for product in products %}
        <div class="card mb-4">
          {% thumbnail product.image "250x250" crop="center" as image %}
            <img class="img-fluid rounded" src="{{ image.url }}" style="width: 177px;" alt="">
          {% endthumbnail %}
            <div class="card-body">
              <h2 class="card-title"><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></h2>
              <p class="card-text"></p>
              <a href="{{ product.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
            </div>
            <div class="card-footer text-muted">
              {{ product.unit_price|intcomma }} Toman
            </div>
            <form method="POST" action="{% url 'cart:compare' product.id %}">
              {% csrf_token %}
              <input type="hidden" value="{{ product.id }}" name="product">
              <button type="submit" class="btn btn-outline-danger">Compare</button>
            </form>
          </div>
          {% endfor %}


        <!-- Pagination -->
        <ul class="pagination justify-content-center mb-4">
          
            {% if products.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ products.previous_page_number }}&{{ data }}">&larr; previous</a>
            </li>
            {% endif %}

            {% if products.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ products.previous_page_number }}&{{ data }}">{{ products.previous_page_number }}</a>
            </li>
            {% endif %}
          
          <li class="page-item {% if page_num == page_num %} active {% endif %}"><a class="page-link" href="?page={{ products.number }}&{{ data }}">{{ products.number }}</a></li>
          
          {% if products.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ products.next_page_number }}&{{ data }}">{{ products.next_page_number }}</a>
            </li>
            {% endif %}

            {% if products.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ products.next_page_number }}&{{ data }}">next &rarr;</a>
            </li>
            {% endif %}
          
          
        </ul>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card mb-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <form>
                Search:
                  <input name="search" class="form-control">
                  <input type="submit" class="btn btn-secondary" value="Go!" type="button">
              </form>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  {% for category in categories %}
                  <li>
                    <a href="{{ category.get_absolute_url }}">{{ category.title }}</a>
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            <form>
              <div class='multi-range' data-lbound='{{ min_price }}' data-ubound='{{ max_price }}'>
                <hr />
                <input type='range' name="price_gte"
                       min='{{ min_price }}' max='{{ max_price }}' step='10000' value='{{ min_price }}' 
                       oninput='this.parentNode.dataset.lbound=this.value;'
                />
                <input type='range' name="price_lte"
                       min='{{ min_price }}' max='{{ max_price }}' step='10000' value='{{ max_price }}' 
                       oninput='this.parentNode.dataset.ubound=this.value;'
                />
            </div><br>

            <label>Brand:
              {{ filter.form.brand }}
            </label><br>
            <label>Color:
              {{ filter.form.color }}
            </label><br>
            <label>Size:
              {{ filter.form.size }}
            </label><br>

            <button type="submit" class="btn btn-outline-danger">Filter</button>

            <div style="display: none;">
              {{ filter.form.unit_price }}
              {{ filter.form.create }}
              {{ filter.form.sell }}
          </div>
            </form>
            <link rel="stylesheet" href="{% static 'css/multi_range.css' %}">
          </div>

        </div>

      </div>

      <form style="display: none;">
        {{ filter.form.price_gte }}
        {{ filter.form.price_lte }}
        {% if 'search' in request.GET %}
        {{ form }}
        {% endif %}
        <button type="submit">Filter</button>
      </form>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
{% endblock %}